# -*- coding: utf-8 -*-
"""PasswordApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLhH8_zaotnIPiIfq0st1U4KFIeOCUd1
"""

import random
import string
import secrets

# Display name and registration number before executing
print("Faheem Aslam")
print("Registration Number: F2020065160")
print("-" * 50)

# Function to generate a secure password
def generate_password(length=16):
    if length < 12:
        print("Password length should be at least 12 characters for security purposes.")
        return None

    # Define character sets for password creation
    lowercase = string.ascii_lowercase
    uppercase = string.ascii_uppercase
    digits = string.digits
    special_characters = string.punctuation

    # Combine all characters
    all_characters = lowercase + uppercase + digits + special_characters

    # Use secrets to generate a cryptographically secure password
    password = ''.join(secrets.choice(all_characters) for i in range(length))

    # Ensure the password contains at least one character from each set
    while not (any(c.islower() for c in password) and
               any(c.isupper() for c in password) and
               any(c.isdigit() for c in password) and
               any(c in special_characters for c in password)):
        password = ''.join(secrets.choice(all_characters) for i in range(length))

    return password

# Generate and print the password
password = generate_password()

# Display the generated password
if password:
    print("Generated Password: ", password)

# Display name and registration number after executing
print("-" * 50)
print("Faheem Aslam")
print("Registration Number: F2020065160")